#!/bin/bash

# OpenSpec Skill Package Installer v2.0.0

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHARED_HOME="$HOME/.openspec"
SHARED_CONFIG="$SHARED_HOME/.opsx-config.yaml"
MANIFEST_DIR="$SHARED_HOME/manifests"

PLATFORM=""
WORKSPACE=""
DRY_RUN=false

usage() {
    cat <<USAGE
Usage: ./install.sh --platform <claude|codex|opencode|gemini|openclaw> [--workspace <path>] [--dry-run]
USAGE
}

run() {
    if [ "$DRY_RUN" = true ]; then
        echo "[dry-run] $*"
    else
        eval "$@"
    fi
}

while [ $# -gt 0 ]; do
    case "$1" in
        --platform)
            PLATFORM="${2:-}"
            shift 2
            ;;
        --workspace)
            WORKSPACE="${2:-}"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1"
            usage
            exit 1
            ;;
    esac
done

if [ -z "$PLATFORM" ]; then
    echo "Error: --platform is required"
    usage
    exit 1
fi

case "$PLATFORM" in
    claude) RULE_FILE="CLAUDE.md" ;;
    codex|opencode|openclaw) RULE_FILE="AGENTS.md" ;;
    gemini) RULE_FILE="GEMINI.md" ;;
    *)
        echo "Error: unsupported platform '$PLATFORM'"
        usage
        exit 1
        ;;
esac

PLATFORM_HOME="$HOME/.${PLATFORM}"
PLATFORM_COMMANDS_DIR="$PLATFORM_HOME/commands"
PLATFORM_OPSX_DIR="$PLATFORM_COMMANDS_DIR/opsx"
PLATFORM_SKILL_DIR="$PLATFORM_HOME/skills/openspec-workflow"
SHARED_SKILL_DIR="$SHARED_HOME/skills/openspec-workflow"
SHARED_COMMANDS_DIR="$SHARED_HOME/commands"
SHARED_OPSX_DIR="$SHARED_COMMANDS_DIR/opsx"

if [ -z "$WORKSPACE" ]; then
    WORKSPACE="$PWD"
fi

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="$SHARED_HOME/backups/install-$PLATFORM-$TIMESTAMP"
MANIFEST_FILE="$MANIFEST_DIR/$PLATFORM.manifest"

echo "🚀 OpenSpec Skill Package v2.0.0 installer"
echo "Platform: $PLATFORM"
echo "Workspace: $WORKSPACE"
echo "Rule file: $RULE_FILE"
[ "$DRY_RUN" = true ] && echo "Mode: dry-run"
echo

run "mkdir -p \"$SHARED_HOME\" \"$MANIFEST_DIR\""

record_manifest() {
    if [ "$DRY_RUN" = false ]; then
        echo "$1" >> "$MANIFEST_FILE"
    fi
}

copy_file() {
    local src="$1"
    local dst="$2"
    run "mkdir -p \"$(dirname "$dst")\""
    run "cp \"$src\" \"$dst\""
    record_manifest "$dst"
}

copy_md_dir() {
    local src_dir="$1"
    local dst_dir="$2"
    local f
    while IFS= read -r f; do
        local rel="${f#${src_dir}/}"
        copy_file "$f" "$dst_dir/$rel"
    done < <(find "$src_dir" -type f -name '*.md' | sort)
}

# Backup existing platform files only.
if [ "$DRY_RUN" = false ]; then
    mkdir -p "$BACKUP_DIR"
    [ -d "$PLATFORM_COMMANDS_DIR" ] && cp -r "$PLATFORM_COMMANDS_DIR" "$BACKUP_DIR/" || true
    [ -d "$PLATFORM_SKILL_DIR" ] && cp -r "$PLATFORM_SKILL_DIR" "$BACKUP_DIR/" || true
fi

# Install shared bundle used by /openspec --doc and shared config.
run "mkdir -p \"$SHARED_SKILL_DIR\" \"$SHARED_OPSX_DIR\""
copy_md_dir "$SCRIPT_DIR/skills/openspec-workflow" "$SHARED_SKILL_DIR"
copy_md_dir "$SCRIPT_DIR/commands/opsx" "$SHARED_OPSX_DIR"
copy_file "$SCRIPT_DIR/commands/openspec.md" "$SHARED_COMMANDS_DIR/openspec.md"

# Install platform bundle.
run "mkdir -p \"$PLATFORM_OPSX_DIR\" \"$PLATFORM_SKILL_DIR\""

# Reset manifest for this platform on each install.
if [ "$DRY_RUN" = false ]; then
    : > "$MANIFEST_FILE"
fi

copy_md_dir "$SCRIPT_DIR/commands/opsx" "$PLATFORM_OPSX_DIR"
copy_file "$SCRIPT_DIR/commands/openspec.md" "$PLATFORM_COMMANDS_DIR/openspec.md"
copy_md_dir "$SCRIPT_DIR/skills/openspec-workflow" "$PLATFORM_SKILL_DIR"

# Migrate legacy Claude-only config if needed.
if [ "$DRY_RUN" = false ] && [ ! -f "$SHARED_CONFIG" ] && [ -f "$HOME/.claude/.opsx-config.yaml" ]; then
    cp "$HOME/.claude/.opsx-config.yaml" "$BACKUP_DIR/legacy-claude-config.yaml"
fi

CURRENT_LANGUAGE="zh"
if [ -f "$SHARED_CONFIG" ]; then
    CURRENT_LANGUAGE="$(grep -E '^[[:space:]]*language:' "$SHARED_CONFIG" | head -n1 | sed -E 's/^[[:space:]]*language:[[:space:]]*"?([^"[:space:]#]+)"?.*$/\1/')"
fi
if [ -z "$CURRENT_LANGUAGE" ]; then
    CURRENT_LANGUAGE="zh"
fi

run "cat > \"$SHARED_CONFIG\" <<CFG
# OpenSpec Local Skill Configuration
# Managed by /openspec meta-commands

version: \"2.0.0\"
platform: \"$PLATFORM\"  # claude | codex | opencode | gemini | openclaw
language: \"$CURRENT_LANGUAGE\"      # en | zh
ruleFile: \"$RULE_FILE\"
CFG"

# Optional: seed workspace rule file if missing
TARGET_RULE_FILE="$WORKSPACE/$RULE_FILE"
if [ "$DRY_RUN" = false ] && [ ! -f "$TARGET_RULE_FILE" ]; then
    cat > "$TARGET_RULE_FILE" <<RULE
# Project Constraints

Generated by /opsx:rules. Run /opsx:rules <type> [profile] to refresh constraints.
RULE
fi

echo
echo "✅ Installation complete"
echo "- Shared config: $SHARED_CONFIG"
echo "- Platform manifest: $MANIFEST_FILE"
echo "- Backup dir: $BACKUP_DIR"
echo "- Commands: $PLATFORM_COMMANDS_DIR"
echo "- Skill: $PLATFORM_SKILL_DIR"
echo "- Workspace rule file: $TARGET_RULE_FILE"
